# Generated by Django 5.2.15 on 2026-06-21 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Youth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300, verbose_name="To'liq ismi")),
                ('birth_date', models.DateField(verbose_name="Tug'ilgan sana")),
                ('address', models.CharField(max_length=500, verbose_name='Manzil')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('category', models.CharField(choices=[('ijtimoiy', 'Ijtimoiy himoyaga muhtoj'), ('imkoniyati_cheklangan', 'Imkoniyati cheklangan'), ('xatarli', 'Xavfli oiladan'), ('yetim', "Yetim yoki yolg'iz"), ('ishsiz', 'Ishsiz yosh'), ('other', 'Boshqa')], default='other', max_length=50, verbose_name='Kategoriya')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youths', to='accounts.organization', verbose_name='MFY')),
                ('rahbar', models.ForeignKey(blank=True, limit_choices_to={'role': 'rahbar'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_youths', to=settings.AUTH_USER_MODEL, verbose_name="Mas'ul Rahbar")),
                ('yetakchi', models.ForeignKey(blank=True, limit_choices_to={'role': 'yetakchi'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_youths', to=settings.AUTH_USER_MODEL, verbose_name="Mas'ul Yetakchi")),
            ],
            options={
                'verbose_name': 'Yosh',
                'verbose_name_plural': 'Yoshlar',
                'ordering': ['full_name'],
            },
        ),
    ]
