# Generated by Django 5.2.15 on 2026-06-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youth',
            name='category',
            field=models.CharField(choices=[('yot_goya', "Yot g'oyalar ta'siriga tushib qolganlar"), ('sudlangan', 'Ilgari sudlanganlar (probatsiya/profilaktika)'), ('mehribonlik', 'Mehribonlik uyidan chiqqanlar'), ('probatsiya', 'Probatsiya nazoratidagilar'), ('ijtimoiy', 'Ijtimoiy himoyaga muhtoj'), ('imkoniyati_cheklangan', 'Imkoniyati cheklangan'), ('xatarli', 'Xavfli oiladan'), ('yetim', "Yetim yoki yolg'iz"), ('ishsiz', 'Ishsiz yosh'), ('other', 'Boshqa')], default='other', max_length=50, verbose_name='Kategoriya'),
        ),
    ]
