# Generated by Django 5.2.15 on 2026-06-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin (Nazoratchi)'), ('rahbar', 'Rahbar (Ijrochi)'), ('yetakchi', 'Yetakchi (Verifier)'), ('user', 'Oddiy foydalanuvchi')], default='user', max_length=20, verbose_name='Rol'),
        ),
    ]
