# Generated by Django 5.2.15 on 2026-06-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_normalized',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Telefon (raqamlar)'),
        ),
    ]
