# Generated by Django 5.2.15 on 2026-06-21 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('youth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='Harakat')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name="Ob'ekt ID")),
                ('details', models.JSONField(default=dict, verbose_name='Tafsilotlar')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Harakat jurnali',
                'verbose_name_plural': 'Harakat jurnallari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Uchrashuv vaqti')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Kenglik (lat)')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Uzunlik (lng)')),
                ('location_address', models.CharField(blank=True, max_length=500, verbose_name='Manzil matni')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='meetings/', verbose_name='Rasm')),
                ('photo_taken_at', models.DateTimeField(blank=True, null=True, verbose_name='Rasm olingan vaqt')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('verified', 'Tasdiqlandi'), ('rejected', 'Rad etildi'), ('impossible', 'Uchrashuv imkonsiz'), ('force_approved', 'Majburiy tasdiqlandi')], default='pending', max_length=20, verbose_name='Holat')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('impossible_reason', models.TextField(blank=True, verbose_name='Imkonsizlik sababi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rahbar', models.ForeignKey(limit_choices_to={'role': 'rahbar'}, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL, verbose_name='Rahbar')),
                ('youth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='youth.youth', verbose_name='Yosh')),
            ],
            options={
                'verbose_name': 'Uchrashuv',
                'verbose_name_plural': 'Uchrashuvlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/', verbose_name='PDF fayl')),
                ('qr_code', models.CharField(max_length=100, unique=True, verbose_name='QR kod')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='meetings.meeting', verbose_name='Uchrashuv')),
            ],
            options={
                'verbose_name': 'Hujjat',
                'verbose_name_plural': 'Hujjatlar',
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holat')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rad etish sababi')),
                ('admin_status', models.CharField(choices=[('none', 'Kerak emas'), ('pending', 'Admin tekshiruvi kerak'), ('approved', 'Admin tasdiqladi'), ('rejected', 'Admin rad etdi')], default='none', max_length=20, verbose_name='Admin holati')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin izohi')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlanish vaqti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='meetings.meeting', verbose_name='Uchrashuv')),
                ('verifier', models.ForeignKey(limit_choices_to={'role': 'yetakchi'}, on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL, verbose_name='Yetakchi')),
            ],
            options={
                'verbose_name': 'Tasdiqlash',
                'verbose_name_plural': 'Tasdiqlashlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
