# Generated by Django 5.2.15 on 2026-06-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64, unique=True, verbose_name='Session ID')),
                ('telegram_id', models.BigIntegerField(verbose_name='Telegram ID')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='camera/', verbose_name='Rasm 1')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='camera/', verbose_name='Rasm 2')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='Yuborildi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kamera sessiyasi',
                'verbose_name_plural': 'Kamera sessiyalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
